### ISSUE TITLE
Jar file is created without no main manifest attribute.

### ISSUE THREAD

**Issue by jssprasanna** [Mestway/SimpleSynthesizer#1]
Thanks a ton for this awesome Scythe :-)
I see that jar files are created with no main manifest attribute. Request you to rectify the same.

However I was able to run the same using
"java -cp SimpleSynthesizer.jar main.Main path/to/the/example/file SymbolicEnumerator 2"

Thanks
  -Swamy

**Comment by Mestway** [comment]
Hi! Thank you for your interest! :)

I'm sorry that the instructions on the master branch is out of date. You can visit our stable version  at https://github.com/Mestway/Scythe/tree/pldi-snapshot.

Secondly, when running a jar file, you are expected to use "java -jar" instead of "java -cp".

Let me know if there is any other problem!
-Chenglong
